server:
  port: 9201
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.168.217.136:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
